version: "3.3"

services:
  com_db:
    container_name: com_db
    image: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    ports:
      - 8806:3306
    volumes:
      - ./system/mysql/conf.d:/etc/mysql/conf.d
      - ./system/mysql/data:/var/lib/mysql
